version: '3.1'
services:
  database:
    image: postgres:10.3-alpine
    container_name: library_database
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./database/app/scripts/01-create_db_app_library.sql:/docker-entrypoint-initdb.d/01.sql
      - ./database/app/scripts/02-insert_data_app_library.sql:/docker-entrypoint-initdb.d/02.sql
      # - ./database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app_library
      - POSTGRES_USER=admin_ocp
      - POSTGRES_PASSWORD=Shangri_La
  web-service:
    image: shinyay/docker-glassfish5
    container_name: library_web-service
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./web-service/app/datasource.properties:/datasource.properties
      - ./web-service/app/library.war:/glassfish5/glassfish/domains/domain1/autodeploy/library.war
      - ./web-service/logs:/glassfish5/glassfish/domains/domain1/logs
    ports:
      - 4848:4848
      # - 8080:8080
      - 8081:8080
      - 8181:8181
  batch:
    image: nboueme/library-batch
    container_name: library_batch
    volumes:
      - ./batch/logs:/logs
  web-application:
    image: shinyay/docker-glassfish5
    container_name: library_web-application
    hostname: 127.0.0.1
    volumes:
      - ./share/images:/images
      - ./web-application/app/Library.war:/glassfish5/glassfish/domains/domain1/autodeploy/Library.war
      - ./web-application/logs:/glassfish5/glassfish/domains/domain1/logs
    ports:
      - 4949:4848
      - 80:8080
      - 8282:8181