INSERT INTO public.type_work (id, type_work) VALUES (1, 'Science-fiction');
INSERT INTO public.type_work (id, type_work) VALUES (2, 'Anticipation');
INSERT INTO public.type_work (id, type_work) VALUES (3, 'Cyberpunk');
INSERT INTO public.type_work (id, type_work) VALUES (4, 'Steampunk');
INSERT INTO public.type_work (id, type_work) VALUES (5, 'Space Opera');
INSERT INTO public.type_work (id, type_work) VALUES (6, 'Science-fiction humouristique');
INSERT INTO public.type_work (id, type_work) VALUES (7, 'Fantasy');
INSERT INTO public.type_work (id, type_work) VALUES (8, 'Fantastique');
INSERT INTO public.type_work (id, type_work) VALUES (9, 'Horreur');
INSERT INTO public.type_work (id, type_work) VALUES (10, 'Aventure');
INSERT INTO public.type_work (id, type_work) VALUES (11, 'Biographie');
INSERT INTO public.type_work (id, type_work) VALUES (12, 'Conte');
INSERT INTO public.type_work (id, type_work) VALUES (13, 'Épopée');
INSERT INTO public.type_work (id, type_work) VALUES (14, 'Nouvelle');
INSERT INTO public.type_work (id, type_work) VALUES (15, 'Témoignage');
INSERT INTO public.type_work (id, type_work) VALUES (16, 'Théâtre');
INSERT INTO public.type_work (id, type_work) VALUES (17, 'Roman');
INSERT INTO public.type_work (id, type_work) VALUES (18, 'Littérature française');

ALTER SEQUENCE type_work_id_seq RESTART WITH 19;