INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (1, 'M', 'Gandalf', null, null, null, null, null, null, 'lotr_gandalf@gmail.com', '$2a$10$qbU443eBFmR2A5zXq8Mw9.BEOMnduuoBizfhDKWux/8gQW8PJVomO', '/image/user/user-1.jpg', 'admin', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (2, 'M', 'Aragorn', null, null, null, null, null, null, 'lotr_aragorn@gmail.com', '$2a$10$rr0wbU8OV9ppLpNxEUHwxOIIPMMg.O8O2GsCfxB8JL5kdKcNUAwCW', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (3, 'M', 'Legolas', null, null, null, null, null, null, 'lotr_legolas@gmail.com', '$2a$10$J9w8fgGg6vKeDXThTkOVhO0h.rCQWSH4eJz591kwcVqVJiouXh.8O', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (4, 'M', 'Frodon', 'Sacquet', null, null, null, null, null, 'lotr_frodon@gmail.com', '$2a$10$wyTdXYKLnpdFnjH3zGFoee7/bRAbiJeK524errYRcBWt3o0diMruu', '/image/user/user-0.png', 'admin', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (5, 'M', 'Sauron', null, null, null, null, null, null, 'lotr_sauron@gmail.com', '$2a$10$YGMoDhqUVYMRu0f83IQ/huv6yMgv2tXe1FSLgtkWnML5DVYRvrzum', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (6, 'M', 'Bilbon', 'Sacquet', null, null, null, null, null, 'lotr_bilbon@gmail.com', '$2a$10$Nmg24tdUrkBaIbcs8lmR7ugVtxCKBiSO63dyOKX9NI/cUsvqVLzzy', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (7, 'M', 'Gollum', null, null, null, null, null, null, 'lotr_gollum@gmail.com', '$2a$10$hosodPaiF22Q10dqKm4B3uJquZLH/Z/iC1c8aE/76MlFW30ppSJQ.', '/image/user/user-7.jpg', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (8, 'Mlle', 'Arwen', null, null, null, null, null, null, 'lotr_arwen@gmail.com', '$2a$10$pYMN6sMP2lDey59HFVOvluhUFOuItnQoYxco/GQW33Tt3TfNsIIEy', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (9, 'M', 'Gimli', null, null, null, null, null, null, 'lotr_gimli@gmail.com', '$2a$10$S..12cUQOTmChECb9RJeZefwvLBkiQO.fbjtpP4vqgJ8WCVSm0QDG', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (10, 'Mlle', 'Galadriel', null, null, null, null, null, null, 'lotr_galadriel@gmail.com', '$2a$10$N9jLNcB8ExLoBRAlvmCIEOatza/qpW80ffyODFShLk.OkiYFIBavG', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (11, 'M', 'Boromir', null, null, null, null, null, null, 'lotr_boromir@gmail.com', '$2a$10$lSezxNt7TdfJCLKlghjdfuZDGtu5LmGs8JJ4Zas98DDVWInBiOXOa', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (12, 'M', 'Saroumane', null, null, null, null, null, null, 'lotr_saroumane@gmail.com', '$2a$10$378ScIVAnl2IChSJOjapPuC7cJFjuKBAIw9fzMNUMzfCcQfvrCD0u', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (13, 'M', 'Samsagace', 'Gamegie', null, null, null, null, null, 'lotr_sam@gmail.com', '$2a$10$mwLW1n5z6xbwwBzmti6CnugExX4rhoaUJCC/dvkqpxNv1LvCyeMka', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (14, 'M', 'Elrond', 'Peredhel', '0532-01-01', null, null, 'Imladris', null, 'lotr_elrond@gmail.com', '$2a$10$/kjZPqp/X5I9E6mskkdn6eE5SC5g1/ntvN9dNgyWR4RHg32ADQ5TO', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (15, 'M', 'Peregrin', 'Touque', null, null, null, null, null, 'lotr_peregrin@gmail.com', '$2a$10$qw0FsoyHNLhXW.dW9GbyLuVbfUfFCEcJmEZieWYwQ9ZUr7gJmCLSe', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);
INSERT INTO public.user_account (id, title, first_name, last_name, birth_date, address, postal_code, city, phone_number, email, password, image_url, role, created_at, updated_at) VALUES (16, 'M', 'Meriadoc', 'Brandebouc', null, null, null, null, null, 'lotr_meriadoc@gmail.com', '$2a$10$Zn6XP0k7X1QwpTLiciAOD.q51d4iPhIT7CA0QDhmrTj2nCKW/C3yu', '/image/user/user-0.png', 'user', '2017-12-27 17:57:53', null);

ALTER SEQUENCE user_account_id_seq RESTART WITH 17;